SELECT DISTINCT "KESÝNTÝ_NEDENÝNE_ÝLÝÞKÝN_AÇIKLAMA" FROM KESÝNTÝ 
SELECT
MIN(BAÞLAMA_TARÝHÝ_VE_ZAMANI) AS En_Erken_Baþlama_Tarihi,
MAX(BAÞLAMA_TARÝHÝ_VE_ZAMANI) AS En_Geç_Baþlama_Tarihi 
FROM KESÝNTÝ 
SELECT ROUND(AVG(KESÝNTÝ_SÜRESÝ), 2) AS KESÝNTÝ_SÜRESÝ_ORTALAMA FROM KESÝNTÝ 
UPDATE KESÝNTÝ SET TOPLAM_KENTSEL_OG = KENTSEL_OG + KENTSEL_AG 
SELECT SÜREYE_GÖRE, COUNT(*) AS KESÝNTÝ_SAYISI
FROM KESÝNTÝ
GROUP BY SÜREYE_GÖRE
SELECT KAYNAÐA_GÖRE, COUNT(*) AS KAYNAK_SAYISI 
FROM KESÝNTÝ 
GROUP BY KAYNAÐA_GÖRE
ORDER BY KAYNAK_SAYISI DESC
SELECT * FROM KESÝNTÝ
WHERE BÝLDÝRÝME_GÖRE > '21-07-2021'
UPDATE KESÝNTÝ SET KESÝNTÝ_SÜRESÝ = DATEDIFF(HOUR, BAÞLAMA_TARÝHÝ_VE_ZAMANI, SONA_ERME_TARÝHÝ_VE_ZAMANI)
SELECT 
SUM(KENTSEL_OG + KENTSEL_AG) AS KENTSEL_KESÝNTÝ_SAYISI,
SUM(KIRSAL_AG + KIRSAL_OG) AS KIRSAL_KESÝNTÝ_SAYISI
FROM KESÝNTÝ
SELECT YEAR(BAÞLAMA_TARÝHÝ_VE_ZAMANI) AS YIL,
MONTH(BAÞLAMA_TARÝHÝ_VE_ZAMANI) AS AY,
SUM(KESÝNTÝ_SÜRESÝ) AS TOPLAM_KESÝNTÝ_SÜRESÝ FROM KESÝNTÝ
GROUP BY YEAR(BAÞLAMA_TARÝHÝ_VE_ZAMANI),MONTH(BAÞLAMA_TARÝHÝ_VE_ZAMANI) 



